/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface DSGuardFactoryInterface extends ethers.utils.Interface {
  functions: {
    "guards(address)": FunctionFragment;
    "isGuard(address)": FunctionFragment;
    "newGuard(bool,address,address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "guards", values: [string]): string;
  encodeFunctionData(functionFragment: "isGuard", values: [string]): string;
  encodeFunctionData(
    functionFragment: "newGuard",
    values: [boolean, string, string]
  ): string;

  decodeFunctionResult(functionFragment: "guards", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isGuard", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "newGuard", data: BytesLike): Result;

  events: {};
}

export class DSGuardFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: DSGuardFactoryInterface;

  functions: {
    guards(arg0: string, overrides?: CallOverrides): Promise<[string]>;

    isGuard(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    newGuard(
      permitFurucombo: boolean,
      furucombo: string,
      dsProxy: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  guards(arg0: string, overrides?: CallOverrides): Promise<string>;

  isGuard(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  newGuard(
    permitFurucombo: boolean,
    furucombo: string,
    dsProxy: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    guards(arg0: string, overrides?: CallOverrides): Promise<string>;

    isGuard(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    newGuard(
      permitFurucombo: boolean,
      furucombo: string,
      dsProxy: string,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    guards(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    isGuard(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    newGuard(
      permitFurucombo: boolean,
      furucombo: string,
      dsProxy: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    guards(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isGuard(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    newGuard(
      permitFurucombo: boolean,
      furucombo: string,
      dsProxy: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
