/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface HUniswapV3Interface extends ethers.utils.Interface {
  functions: {
    "MSG_SENDER_KEY()": FunctionFragment;
    "NATIVE_TOKEN_ADDRESS()": FunctionFragment;
    "PERCENTAGE_BASE()": FunctionFragment;
    "POSTPROCESS_SIG()": FunctionFragment;
    "ROUTER()": FunctionFragment;
    "WETH()": FunctionFragment;
    "cache(bytes32)": FunctionFragment;
    "exactInput(bytes,uint256,uint256)": FunctionFragment;
    "exactInputFromEther(bytes,uint256,uint256)": FunctionFragment;
    "exactInputSingle(address,address,uint24,uint256,uint256,uint160)": FunctionFragment;
    "exactInputSingleFromEther(address,uint24,uint256,uint256,uint160)": FunctionFragment;
    "exactInputSingleToEther(address,uint24,uint256,uint256,uint160)": FunctionFragment;
    "exactInputToEther(bytes,uint256,uint256)": FunctionFragment;
    "exactOutput(bytes,uint256,uint256)": FunctionFragment;
    "exactOutputFromEther(bytes,uint256,uint256)": FunctionFragment;
    "exactOutputSingle(address,address,uint24,uint256,uint256,uint160)": FunctionFragment;
    "exactOutputSingleFromEther(address,uint24,uint256,uint256,uint160)": FunctionFragment;
    "exactOutputSingleToEther(address,uint24,uint256,uint256,uint160)": FunctionFragment;
    "exactOutputToEther(bytes,uint256,uint256)": FunctionFragment;
    "getContractName()": FunctionFragment;
    "postProcess()": FunctionFragment;
    "stack(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "MSG_SENDER_KEY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "NATIVE_TOKEN_ADDRESS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PERCENTAGE_BASE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "POSTPROCESS_SIG",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "ROUTER", values?: undefined): string;
  encodeFunctionData(functionFragment: "WETH", values?: undefined): string;
  encodeFunctionData(functionFragment: "cache", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "exactInput",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "exactInputFromEther",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "exactInputSingle",
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "exactInputSingleFromEther",
    values: [string, BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "exactInputSingleToEther",
    values: [string, BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "exactInputToEther",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "exactOutput",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "exactOutputFromEther",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "exactOutputSingle",
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "exactOutputSingleFromEther",
    values: [string, BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "exactOutputSingleToEther",
    values: [string, BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "exactOutputToEther",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getContractName",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "postProcess",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "stack", values: [BigNumberish]): string;

  decodeFunctionResult(
    functionFragment: "MSG_SENDER_KEY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "NATIVE_TOKEN_ADDRESS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PERCENTAGE_BASE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "POSTPROCESS_SIG",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ROUTER", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "WETH", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cache", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "exactInput", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "exactInputFromEther",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "exactInputSingle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "exactInputSingleFromEther",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "exactInputSingleToEther",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "exactInputToEther",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "exactOutput",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "exactOutputFromEther",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "exactOutputSingle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "exactOutputSingleFromEther",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "exactOutputSingleToEther",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "exactOutputToEther",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContractName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "postProcess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stack", data: BytesLike): Result;

  events: {};
}

export class HUniswapV3 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: HUniswapV3Interface;

  functions: {
    MSG_SENDER_KEY(overrides?: CallOverrides): Promise<[string]>;

    NATIVE_TOKEN_ADDRESS(overrides?: CallOverrides): Promise<[string]>;

    PERCENTAGE_BASE(overrides?: CallOverrides): Promise<[BigNumber]>;

    POSTPROCESS_SIG(overrides?: CallOverrides): Promise<[string]>;

    ROUTER(overrides?: CallOverrides): Promise<[string]>;

    WETH(overrides?: CallOverrides): Promise<[string]>;

    cache(arg0: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    exactInput(
      path: BytesLike,
      amountIn: BigNumberish,
      amountOutMinimum: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    exactInputFromEther(
      path: BytesLike,
      amountIn: BigNumberish,
      amountOutMinimum: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    exactInputSingle(
      tokenIn: string,
      tokenOut: string,
      fee: BigNumberish,
      amountIn: BigNumberish,
      amountOutMinimum: BigNumberish,
      sqrtPriceLimitX96: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    exactInputSingleFromEther(
      tokenOut: string,
      fee: BigNumberish,
      amountIn: BigNumberish,
      amountOutMinimum: BigNumberish,
      sqrtPriceLimitX96: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    exactInputSingleToEther(
      tokenIn: string,
      fee: BigNumberish,
      amountIn: BigNumberish,
      amountOutMinimum: BigNumberish,
      sqrtPriceLimitX96: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    exactInputToEther(
      path: BytesLike,
      amountIn: BigNumberish,
      amountOutMinimum: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    exactOutput(
      path: BytesLike,
      amountOut: BigNumberish,
      amountInMaximum: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    exactOutputFromEther(
      path: BytesLike,
      amountOut: BigNumberish,
      amountInMaximum: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    exactOutputSingle(
      tokenIn: string,
      tokenOut: string,
      fee: BigNumberish,
      amountOut: BigNumberish,
      amountInMaximum: BigNumberish,
      sqrtPriceLimitX96: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    exactOutputSingleFromEther(
      tokenOut: string,
      fee: BigNumberish,
      amountOut: BigNumberish,
      amountInMaximum: BigNumberish,
      sqrtPriceLimitX96: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    exactOutputSingleToEther(
      tokenIn: string,
      fee: BigNumberish,
      amountOut: BigNumberish,
      amountInMaximum: BigNumberish,
      sqrtPriceLimitX96: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    exactOutputToEther(
      path: BytesLike,
      amountOut: BigNumberish,
      amountInMaximum: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getContractName(overrides?: CallOverrides): Promise<[string]>;

    postProcess(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    stack(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;
  };

  MSG_SENDER_KEY(overrides?: CallOverrides): Promise<string>;

  NATIVE_TOKEN_ADDRESS(overrides?: CallOverrides): Promise<string>;

  PERCENTAGE_BASE(overrides?: CallOverrides): Promise<BigNumber>;

  POSTPROCESS_SIG(overrides?: CallOverrides): Promise<string>;

  ROUTER(overrides?: CallOverrides): Promise<string>;

  WETH(overrides?: CallOverrides): Promise<string>;

  cache(arg0: BytesLike, overrides?: CallOverrides): Promise<string>;

  exactInput(
    path: BytesLike,
    amountIn: BigNumberish,
    amountOutMinimum: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  exactInputFromEther(
    path: BytesLike,
    amountIn: BigNumberish,
    amountOutMinimum: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  exactInputSingle(
    tokenIn: string,
    tokenOut: string,
    fee: BigNumberish,
    amountIn: BigNumberish,
    amountOutMinimum: BigNumberish,
    sqrtPriceLimitX96: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  exactInputSingleFromEther(
    tokenOut: string,
    fee: BigNumberish,
    amountIn: BigNumberish,
    amountOutMinimum: BigNumberish,
    sqrtPriceLimitX96: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  exactInputSingleToEther(
    tokenIn: string,
    fee: BigNumberish,
    amountIn: BigNumberish,
    amountOutMinimum: BigNumberish,
    sqrtPriceLimitX96: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  exactInputToEther(
    path: BytesLike,
    amountIn: BigNumberish,
    amountOutMinimum: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  exactOutput(
    path: BytesLike,
    amountOut: BigNumberish,
    amountInMaximum: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  exactOutputFromEther(
    path: BytesLike,
    amountOut: BigNumberish,
    amountInMaximum: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  exactOutputSingle(
    tokenIn: string,
    tokenOut: string,
    fee: BigNumberish,
    amountOut: BigNumberish,
    amountInMaximum: BigNumberish,
    sqrtPriceLimitX96: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  exactOutputSingleFromEther(
    tokenOut: string,
    fee: BigNumberish,
    amountOut: BigNumberish,
    amountInMaximum: BigNumberish,
    sqrtPriceLimitX96: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  exactOutputSingleToEther(
    tokenIn: string,
    fee: BigNumberish,
    amountOut: BigNumberish,
    amountInMaximum: BigNumberish,
    sqrtPriceLimitX96: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  exactOutputToEther(
    path: BytesLike,
    amountOut: BigNumberish,
    amountInMaximum: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getContractName(overrides?: CallOverrides): Promise<string>;

  postProcess(
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  stack(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  callStatic: {
    MSG_SENDER_KEY(overrides?: CallOverrides): Promise<string>;

    NATIVE_TOKEN_ADDRESS(overrides?: CallOverrides): Promise<string>;

    PERCENTAGE_BASE(overrides?: CallOverrides): Promise<BigNumber>;

    POSTPROCESS_SIG(overrides?: CallOverrides): Promise<string>;

    ROUTER(overrides?: CallOverrides): Promise<string>;

    WETH(overrides?: CallOverrides): Promise<string>;

    cache(arg0: BytesLike, overrides?: CallOverrides): Promise<string>;

    exactInput(
      path: BytesLike,
      amountIn: BigNumberish,
      amountOutMinimum: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    exactInputFromEther(
      path: BytesLike,
      amountIn: BigNumberish,
      amountOutMinimum: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    exactInputSingle(
      tokenIn: string,
      tokenOut: string,
      fee: BigNumberish,
      amountIn: BigNumberish,
      amountOutMinimum: BigNumberish,
      sqrtPriceLimitX96: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    exactInputSingleFromEther(
      tokenOut: string,
      fee: BigNumberish,
      amountIn: BigNumberish,
      amountOutMinimum: BigNumberish,
      sqrtPriceLimitX96: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    exactInputSingleToEther(
      tokenIn: string,
      fee: BigNumberish,
      amountIn: BigNumberish,
      amountOutMinimum: BigNumberish,
      sqrtPriceLimitX96: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    exactInputToEther(
      path: BytesLike,
      amountIn: BigNumberish,
      amountOutMinimum: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    exactOutput(
      path: BytesLike,
      amountOut: BigNumberish,
      amountInMaximum: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    exactOutputFromEther(
      path: BytesLike,
      amountOut: BigNumberish,
      amountInMaximum: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    exactOutputSingle(
      tokenIn: string,
      tokenOut: string,
      fee: BigNumberish,
      amountOut: BigNumberish,
      amountInMaximum: BigNumberish,
      sqrtPriceLimitX96: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    exactOutputSingleFromEther(
      tokenOut: string,
      fee: BigNumberish,
      amountOut: BigNumberish,
      amountInMaximum: BigNumberish,
      sqrtPriceLimitX96: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    exactOutputSingleToEther(
      tokenIn: string,
      fee: BigNumberish,
      amountOut: BigNumberish,
      amountInMaximum: BigNumberish,
      sqrtPriceLimitX96: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    exactOutputToEther(
      path: BytesLike,
      amountOut: BigNumberish,
      amountInMaximum: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getContractName(overrides?: CallOverrides): Promise<string>;

    postProcess(overrides?: CallOverrides): Promise<void>;

    stack(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    MSG_SENDER_KEY(overrides?: CallOverrides): Promise<BigNumber>;

    NATIVE_TOKEN_ADDRESS(overrides?: CallOverrides): Promise<BigNumber>;

    PERCENTAGE_BASE(overrides?: CallOverrides): Promise<BigNumber>;

    POSTPROCESS_SIG(overrides?: CallOverrides): Promise<BigNumber>;

    ROUTER(overrides?: CallOverrides): Promise<BigNumber>;

    WETH(overrides?: CallOverrides): Promise<BigNumber>;

    cache(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    exactInput(
      path: BytesLike,
      amountIn: BigNumberish,
      amountOutMinimum: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    exactInputFromEther(
      path: BytesLike,
      amountIn: BigNumberish,
      amountOutMinimum: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    exactInputSingle(
      tokenIn: string,
      tokenOut: string,
      fee: BigNumberish,
      amountIn: BigNumberish,
      amountOutMinimum: BigNumberish,
      sqrtPriceLimitX96: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    exactInputSingleFromEther(
      tokenOut: string,
      fee: BigNumberish,
      amountIn: BigNumberish,
      amountOutMinimum: BigNumberish,
      sqrtPriceLimitX96: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    exactInputSingleToEther(
      tokenIn: string,
      fee: BigNumberish,
      amountIn: BigNumberish,
      amountOutMinimum: BigNumberish,
      sqrtPriceLimitX96: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    exactInputToEther(
      path: BytesLike,
      amountIn: BigNumberish,
      amountOutMinimum: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    exactOutput(
      path: BytesLike,
      amountOut: BigNumberish,
      amountInMaximum: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    exactOutputFromEther(
      path: BytesLike,
      amountOut: BigNumberish,
      amountInMaximum: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    exactOutputSingle(
      tokenIn: string,
      tokenOut: string,
      fee: BigNumberish,
      amountOut: BigNumberish,
      amountInMaximum: BigNumberish,
      sqrtPriceLimitX96: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    exactOutputSingleFromEther(
      tokenOut: string,
      fee: BigNumberish,
      amountOut: BigNumberish,
      amountInMaximum: BigNumberish,
      sqrtPriceLimitX96: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    exactOutputSingleToEther(
      tokenIn: string,
      fee: BigNumberish,
      amountOut: BigNumberish,
      amountInMaximum: BigNumberish,
      sqrtPriceLimitX96: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    exactOutputToEther(
      path: BytesLike,
      amountOut: BigNumberish,
      amountInMaximum: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getContractName(overrides?: CallOverrides): Promise<BigNumber>;

    postProcess(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    stack(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    MSG_SENDER_KEY(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    NATIVE_TOKEN_ADDRESS(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    PERCENTAGE_BASE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    POSTPROCESS_SIG(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ROUTER(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    WETH(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    cache(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    exactInput(
      path: BytesLike,
      amountIn: BigNumberish,
      amountOutMinimum: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    exactInputFromEther(
      path: BytesLike,
      amountIn: BigNumberish,
      amountOutMinimum: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    exactInputSingle(
      tokenIn: string,
      tokenOut: string,
      fee: BigNumberish,
      amountIn: BigNumberish,
      amountOutMinimum: BigNumberish,
      sqrtPriceLimitX96: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    exactInputSingleFromEther(
      tokenOut: string,
      fee: BigNumberish,
      amountIn: BigNumberish,
      amountOutMinimum: BigNumberish,
      sqrtPriceLimitX96: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    exactInputSingleToEther(
      tokenIn: string,
      fee: BigNumberish,
      amountIn: BigNumberish,
      amountOutMinimum: BigNumberish,
      sqrtPriceLimitX96: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    exactInputToEther(
      path: BytesLike,
      amountIn: BigNumberish,
      amountOutMinimum: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    exactOutput(
      path: BytesLike,
      amountOut: BigNumberish,
      amountInMaximum: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    exactOutputFromEther(
      path: BytesLike,
      amountOut: BigNumberish,
      amountInMaximum: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    exactOutputSingle(
      tokenIn: string,
      tokenOut: string,
      fee: BigNumberish,
      amountOut: BigNumberish,
      amountInMaximum: BigNumberish,
      sqrtPriceLimitX96: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    exactOutputSingleFromEther(
      tokenOut: string,
      fee: BigNumberish,
      amountOut: BigNumberish,
      amountInMaximum: BigNumberish,
      sqrtPriceLimitX96: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    exactOutputSingleToEther(
      tokenIn: string,
      fee: BigNumberish,
      amountOut: BigNumberish,
      amountInMaximum: BigNumberish,
      sqrtPriceLimitX96: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    exactOutputToEther(
      path: BytesLike,
      amountOut: BigNumberish,
      amountInMaximum: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getContractName(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    postProcess(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    stack(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
