/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IInvocationHookInterface extends ethers.utils.Interface {
  functions: {
    "currentRepaymentAmount()": FunctionFragment;
    "currentSender()": FunctionFragment;
    "currentTokenAddress()": FunctionFragment;
    "currentTokenAmount()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "currentRepaymentAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentSender",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentTokenAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentTokenAmount",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "currentRepaymentAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentSender",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentTokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentTokenAmount",
    data: BytesLike
  ): Result;

  events: {};
}

export class IInvocationHook extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IInvocationHookInterface;

  functions: {
    currentRepaymentAmount(overrides?: CallOverrides): Promise<[BigNumber]>;

    currentSender(overrides?: CallOverrides): Promise<[string]>;

    currentTokenAddress(overrides?: CallOverrides): Promise<[string]>;

    currentTokenAmount(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  currentRepaymentAmount(overrides?: CallOverrides): Promise<BigNumber>;

  currentSender(overrides?: CallOverrides): Promise<string>;

  currentTokenAddress(overrides?: CallOverrides): Promise<string>;

  currentTokenAmount(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    currentRepaymentAmount(overrides?: CallOverrides): Promise<BigNumber>;

    currentSender(overrides?: CallOverrides): Promise<string>;

    currentTokenAddress(overrides?: CallOverrides): Promise<string>;

    currentTokenAmount(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    currentRepaymentAmount(overrides?: CallOverrides): Promise<BigNumber>;

    currentSender(overrides?: CallOverrides): Promise<BigNumber>;

    currentTokenAddress(overrides?: CallOverrides): Promise<BigNumber>;

    currentTokenAmount(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    currentRepaymentAmount(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    currentSender(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    currentTokenAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    currentTokenAmount(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
