/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { DSAuthEvents, DSAuthEventsInterface } from "../DSAuthEvents";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "authority",
        type: "address",
      },
    ],
    name: "LogSetAuthority",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    name: "LogSetOwner",
    type: "event",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50603f80601d6000396000f3fe6080604052600080fdfea26469706673582212206855ab8905857c10dc4be1184873c74746ebd1e7d20532c0338fc8f36251b82364736f6c63430008040033";

export class DSAuthEvents__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<DSAuthEvents> {
    return super.deploy(overrides || {}) as Promise<DSAuthEvents>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): DSAuthEvents {
    return super.attach(address) as DSAuthEvents;
  }
  connect(signer: Signer): DSAuthEvents__factory {
    return super.connect(signer) as DSAuthEvents__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): DSAuthEventsInterface {
    return new utils.Interface(_abi) as DSAuthEventsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DSAuthEvents {
    return new Contract(address, _abi, signerOrProvider) as DSAuthEvents;
  }
}
