/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { DSGuardEvents, DSGuardEventsInterface } from "../DSGuardEvents";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "src",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "dst",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "sig",
        type: "bytes32",
      },
    ],
    name: "LogForbid",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "src",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "dst",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "sig",
        type: "bytes32",
      },
    ],
    name: "LogPermit",
    type: "event",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50603f80601d6000396000f3fe6080604052600080fdfea2646970667358221220e2ef1609516f1245a80e534d3735a62c9f3bc2a5cb72764ed1fc40920b505bb264736f6c63430008040033";

export class DSGuardEvents__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<DSGuardEvents> {
    return super.deploy(overrides || {}) as Promise<DSGuardEvents>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): DSGuardEvents {
    return super.attach(address) as DSGuardEvents;
  }
  connect(signer: Signer): DSGuardEvents__factory {
    return super.connect(signer) as DSGuardEvents__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): DSGuardEventsInterface {
    return new utils.Interface(_abi) as DSGuardEventsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DSGuardEvents {
    return new Contract(address, _abi, signerOrProvider) as DSGuardEvents;
  }
}
