/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IInvokable, IInvokableInterface } from "../IInvokable";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "execute",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];

export class IInvokable__factory {
  static readonly abi = _abi;
  static createInterface(): IInvokableInterface {
    return new utils.Interface(_abi) as IInvokableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IInvokable {
    return new Contract(address, _abi, signerOrProvider) as IInvokable;
  }
}
