/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IInvocationHook,
  IInvocationHookInterface,
} from "../IInvocationHook";

const _abi = [
  {
    inputs: [],
    name: "currentRepaymentAmount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "currentSender",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "currentTokenAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "currentTokenAmount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IInvocationHook__factory {
  static readonly abi = _abi;
  static createInterface(): IInvocationHookInterface {
    return new utils.Interface(_abi) as IInvocationHookInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IInvocationHook {
    return new Contract(address, _abi, signerOrProvider) as IInvocationHook;
  }
}
