/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IMakerGemJoin, IMakerGemJoinInterface } from "../IMakerGemJoin";

const _abi = [
  {
    inputs: [],
    name: "dec",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "exit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "gem",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "join",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];

export class IMakerGemJoin__factory {
  static readonly abi = _abi;
  static createInterface(): IMakerGemJoinInterface {
    return new utils.Interface(_abi) as IMakerGemJoinInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMakerGemJoin {
    return new Contract(address, _abi, signerOrProvider) as IMakerGemJoin;
  }
}
