/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IMakerChainLog,
  IMakerChainLogInterface,
} from "../IMakerChainLog";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    name: "getAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IMakerChainLog__factory {
  static readonly abi = _abi;
  static createInterface(): IMakerChainLogInterface {
    return new utils.Interface(_abi) as IMakerChainLogInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMakerChainLog {
    return new Contract(address, _abi, signerOrProvider) as IMakerChainLog;
  }
}
