/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  KollateralInvokable,
  KollateralInvokableInterface,
} from "../KollateralInvokable";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "execute",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
];

export class KollateralInvokable__factory {
  static readonly abi = _abi;
  static createInterface(): KollateralInvokableInterface {
    return new utils.Interface(_abi) as KollateralInvokableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): KollateralInvokable {
    return new Contract(address, _abi, signerOrProvider) as KollateralInvokable;
  }
}
